#ifndef _TAL_NOISEMAKER_PRESETS_H_
#define _TAL_NOISEMAKER_PRESETS_H_

// Hardcoded TAL-NoiseMaker factory preset names in the exact order
// the plugin's IUnitInfo/kIsProgramChange parameter expects.
// Extracted from the embedded BinaryData in the native Linux VST3.
// These are fixed factory presets that never change.

#define TAL_NOISEMAKER_PRESET_COUNT 256

static const char *talNoiseMakerPresetNames[TAL_NOISEMAKER_PRESET_COUNT] = {
    "FX Space Train TAL",
    "FX Radeberger FN",
    "FX Whooo! AS",
    "FX Falling Bombs TAL",
    "FX Turbo Loader TAL",
    "FX Digital Aquanaut TAL",
    "FX Swell FN",
    "FX Quitscheentchen FN",
    "FX High Voltage Start TA",
    "FX Break FM",
    "FX Cool Sci Fi Ramp TAL",
    "FX Analog Modem TAL",
    "FX Falling Break TAL",
    "FX SO 24dB Sweep TAL",
    "FX Reverse FM TAL",
    "FX THX for the people TA",
    "FX Another World TAL",
    "FX Raindrops FN",
    "FX Cave Divers TUC",
    "FX Turntable FN",
    "FX Alien Storm TAL",
    "FX Digital Transfer TAL",
    "FX Mobile Noise TAL",
    "FX Breaking Up AS",
    "FX Blubberwasser FN",
    "FX Reso Attack TAL",
    "FX Noiz3machin3 FN",
    "FX Loony Bin AS",
    "FX Bit Shuffla TAL",
    "FX Metallica FN",
    "FX  Jumper TAL",
    "FX Mod Triangle FM TAL",
    "FX Clean Noise Ramp TAL",
    "FX C64 FN",
    "DR 8bit  Kick III FN",
    "DR Kick Nuuuu TAL",
    "DR 8bit Kick FN",
    "DR Perc Tuned Tom TAL",
    "DR Perc Tommer TAL",
    "DR 8bit  Kick II FN",
    "DR Perc Elektro Click TA",
    "DR Kick Universal TAL",
    "DR Kick Clean TAL",
    "DR Hat Reverse TAL",
    "DR Kick Old School TAL",
    "DR Hat Short Moves TAL",
    "DR Clap Maker TAL",
    "DR Perc Bongo Room TAL",
    "DR Snare Snappy TAL",
    "DR Kick Goa TAL",
    "DR Kick Pitch TAL",
    "DR Kick FN",
    "DR Kick Phat TAL",
    "DR Sub Impact TAL",
    "DR Perc Room TAL",
    "DR Kick II FN",
    "DR Crash Space TAL",
    "DR Hat Short TAL",
    "DR HiHat FN",
    "DR Snare Dry TAL",
    "DR Kick III FN",
    "DR Perc Old Zipper TAL",
    "KB Smooth Sine TAL",
    "KB Piano House TAL",
    "KB Glass Star TUC",
    "KB Glockenschlag FN",
    "KB Screetcher TUC",
    "KB Big Synth FN",
    "KB Drops TAL",
    "KB Pop Pluck TUC",
    "KB Ghostly Glomp AS",
    "KB Sawberry Milkshake TU",
    "KB Chimp Organ TUC",
    "KB Dreaming FN",
    "KB White Noise FN",
    "KB E-Piano TAL",
    "BS Mixmiddle FN",
    "BS Juicy Bass TUC",
    "BS Syncetel Bass FN",
    "BS Dark Night FN",
    "BS Energyator FN",
    "BS Jelly Mountain AS",
    "BS LFO Roller FN",
    "BS Wobbler II FN",
    "BS Reso Bass Classic TAL",
    "BS Tock Sick AS",
    "BS Sawlight FN",
    "BS Clean Flat Bass TAL",
    "BS Easy Listener FN",
    "BS SAWbreaker FN",
    "BS Mong AS",
    "BS Crispy bass",
    "BS Eager Beaver AS",
    "BS Flamming Bass FN",
    "BS Hard 80's TAL",
    "BS Wobbler FN",
    "BS C64 Octavebass FN",
    "BS Small Bassist FN",
    "BS Detuned FN",
    "BS Goodspeed FN",
    "BS 007 FN",
    "BS The Island FN",
    "BS Tremolo Bass TAL",
    "BS Noizigian FN",
    "BS Pluggiator FN",
    "BS Bassolead FN",
    "BS D&B Wubler TAL",
    "BS Night And Day FN",
    "BS Whoppy The Fifth TUC",
    "BS Terminator TAL",
    "BS FM Pulse Train TAL",
    "BS 7th Gates FN",
    "BS Basspa FN",
    "BS Bass Deep TAL",
    "BS Knarziger FN",
    "BS Joop Joop 1 AS",
    "BS Sci Fi TAL",
    "BS Tripple Wobbler TAL",
    "BS Big Starter TAL",
    "BS Deep Driver TAL",
    "BS Neon Bass AS",
    "BS Dark Bass TAL",
    "BS Double Whoppy TUC",
    "BS Open Bass FN",
    "BS Justice TAL",
    "BS Wonderland FN",
    "BS Bass is your friend F",
    "BS Slow Filter FN",
    "BS Madskillz FN",
    "BS Fat Side FN",
    "PD Bit Orchestra TAL",
    "PD Glasometer FN",
    "PD  Ringmodded FN",
    "PD Sweet Analogue TAL",
    "PD Padwobbler FN",
    "PD Big Trancer FN",
    "PD Easymat FN",
    "PD Dark Animations FN",
    "PD Gated Pad TAL",
    "PD Lightstorm TUC",
    "PD Parallax Pad AS",
    "PD Spooky Organ TAL",
    "PD Luxury Strings AS",
    "PD Base Pad TAL",
    "PD Floating Pad TAL",
    "PD Fantasy Pad TAL",
    "PD Sun Rise TAL",
    "PD Fuzzy Chorda TAL",
    "PD Twoflower FN",
    "PD Tron TAL",
    "PD Bellomatism FN",
    "PD Ringmod Mod TAL",
    "PD Open Square FN",
    "PD Bursting Pad TAL",
    "PD Dream of '86 TUC",
    "PD Bionic Pad TAL",
    "LD Tranceline FN",
    "LD ModWave AS",
    "LD Everglade Walk TAL",
    "LD D Robot TAL",
    "LD Spook AS",
    "LD Woholead FN",
    "LD Mellow Chord TAL",
    "LD Morph Sync TAL",
    "LD Take Up Strings TAL",
    "LD Rasp Lead AS",
    "LD Slop AS",
    "LD Haunted Strings AS",
    "LD Plastic Attack TAL",
    "LD Marging Fifth AS",
    "LD SYNCElead FN",
    "LD Bon Voyage FN",
    "LD Technoshocker FN",
    "LD Electric Charged TAL",
    "LD Shutter Lead TAL",
    "LD It's Complicated AS",
    "LD FM Sync Voice AS",
    "LD Thin Lead TAL",
    "LD Acid Dist Noisy TAL",
    "LD Lo Fi Party TAL",
    "LD Basic Whapp TUC",
    "LD Mellow Organ TAL",
    "LD Analog Down Glider TA",
    "LD Power Lead TAL",
    "LD FM Pulse Train TAL",
    "LD Pwap AS",
    "LD Ohm Duck Solo TAL",
    "LD Fug Pugly AS",
    "LD Triangle Madness TAL",
    "LD Plucked String TAL",
    "LD Aggggggro TAL",
    "LD Metal Spikes AS",
    "LD Big Dipper AS",
    "LD Drop In Pulse TAL",
    "LD 3D Game Boy TAL",
    "LD Luxury Lead AS",
    "LD Happy go Mucky AS",
    "LD Mod-U-Crush AS",
    "LD High Noon AS",
    "LD Crazy Trumped AS",
    "LD High Voltage Lift TAL",
    "LD Dirty Snow AS",
    "LD Metal Lead TAL",
    "LD Breadbin Burble AS",
    "LD Neon Knife TUC",
    "LD Sci Fi Organ TAL",
    "LD Special Starter TAL",
    "LD Ringing Lead TAL",
    "LD Acid Saw TAL",
    "LD Green Glass Worm TUC",
    "LD Steam Pulse AS",
    "LD Muchos Air TAL",
    "LD The Colour Purple AS",
    "LD Alarm Light TUC",
    "LD Fuzzy Cargo TAL",
    "LD Phasing Saws TAL",
    "LD 8bitter II FN",
    "LD Noisy Sync Lead TAL",
    "LD Funky Mod TAL",
    "LD We Felt Digital TUC",
    "LD Pleutonium FN",
    "LD Croke AS",
    "LD Shiver Stab AS",
    "LD Soft Bell Lead TAL",
    "LD Crazy Triangle Arp TA",
    "LD Resolve 2 AS",
    "LD Metal Wahuuu TAL",
    "LD Delay Filter Step TAL",
    "LD Fuzzy Box TAL",
    "LD Crystal Lead TAL",
    "LD Geiler Patch FN",
    "LD Spring Bell TAL",
    "LD Resobells FN",
    "ARP Infected TAL",
    "ARP 2050 Punk TAL",
    "ARP Phasing Saws TAL",
    "ARP 303 Like FN",
    "ARP Danger Dance TUC",
    "ARP Super Sync TAL",
    "ARP C64 III FN",
    "ARP C64 II FN",
    "ARP Armageddon FN",
    "ARP Demotrack ARP FN",
    "ARP C64 FN",
    "ARP Rumpelkammer FN",
    "ARP 303 Like II FN",
    "ARP On The Run TUC",
    "ARP C64 IV FN",
    "CH Chordionator FN",
    "CH Open Mind FN",
    "CD Universal FN",
    "CH SIDchord FN",
    "CH Chordionator IV FN",
    "CH Chordionator III FN",
    "CH Chordionator II FN",
    "default"
};

#endif
