#include "ButtonMappingDialog.h"
#include "Adapters/SDL2/GUI/SDLEventManager.h"
#include "Application/Controllers/ControlRoom.h"
#include "System/Console/Trace.h"
#include "System/FileSystem/FileSystem.h"
#include <cstdio>
#include <cstring>
#include <fstream>
#include <sys/stat.h>

// The buttons we prompt the user to map, in order
const char *ButtonMappingDialog::stepNames_[MAP_STEP_COUNT] = {
    "UP",
    "DOWN",
    "LEFT",
    "RIGHT",
    "A (confirm)",
    "B (back/alt)",
    "Left Shoulder",
    "Right Shoulder",
    "START",
    "SELECT",
    "Page Back",
    "Page Forward",
};

// The destination URL each step maps to
const char *ButtonMappingDialog::stepDstUrls_[MAP_STEP_COUNT] = {
    "/event/up",
    "/event/down",
    "/event/left",
    "/event/right",
    "/event/a",
    "/event/b",
    "/event/lshoulder",
    "/event/rshoulder",
    "/event/start",
    "/event/select",
    "/event/pgback",
    "/event/pgfwd",
};

ButtonMappingDialog::ButtonMappingDialog(View &view)
    : ModalView(view), currentStep_(0), waitingForRelease_(true) {
    for (int i = 0; i < MAP_STEP_COUNT; i++) {
        captured_[i] = "";
    }
}

ButtonMappingDialog::~ButtonMappingDialog() {
    SDLEventManager::StopCapture();
}

void ButtonMappingDialog::OnFocus() {
    SDLEventManager::StartCapture();
    currentStep_ = 0;
    waitingForRelease_ = true;
    isDirty_ = true;
}

void ButtonMappingDialog::DrawView() {
    int width = 34;
    int height = 7;
    SetWindow(width, height);

    GUITextProperties props;
    SetColor(CD_NORMAL);

    if (currentStep_ >= MAP_STEP_COUNT) {
        // All done
        DrawString(2, 0, "Button mapping complete!", props);
        DrawString(2, 2, "Mapping saved to mapping.xml", props);
        DrawString(2, 4, "Restart app to apply.", props);

        props.invert_ = true;
        DrawString(14, 6, "  OK  ", props);
    } else {
        // Show title
        DrawString(2, 0, "== Button Mapping Setup ==", props);

        // Show progress
        char progress[40];
        snprintf(progress, sizeof(progress), "Step %d of %d",
                 currentStep_ + 1, MAP_STEP_COUNT);
        DrawString(2, 2, progress, props);

        // Show what to press
        char prompt[40];
        snprintf(prompt, sizeof(prompt), "Press: %s",
                 stepNames_[currentStep_]);
        SetColor(CD_HILITE1);
        DrawString(2, 4, prompt, props);

        // Show last captured (if waiting for release after capture)
        if (!captured_[currentStep_].empty()) {
            SetColor(CD_CURSOR);
            char cap[40];
            snprintf(cap, sizeof(cap), "Got: %s",
                     captured_[currentStep_].c_str());
            DrawString(2, 5, cap, props);
        }

        // Cancel hint
        SetColor(CD_NORMAL);
        DrawString(2, 6, "(Hold B to cancel)", props);
    }
}

void ButtonMappingDialog::ProcessButtonMask(unsigned short mask, bool pressed) {
    if (!pressed) return;

    // If mapping is done, any press closes the dialog
    if (currentStep_ >= MAP_STEP_COUNT) {
        EndModal(1); // success
        return;
    }

    // Check for captured raw input from the event manager
    std::string cap = SDLEventManager::ConsumeCapture();
    if (!cap.empty() && !waitingForRelease_) {
        // Store this capture
        captured_[currentStep_] = cap;
        currentStep_++;
        waitingForRelease_ = true;
        isDirty_ = true;

        // If all steps done, write the file and stop capture
        if (currentStep_ >= MAP_STEP_COUNT) {
            SDLEventManager::StopCapture();
            WriteMappingFile();
        }
        return;
    }

    // After a capture, wait until the user releases everything before
    // accepting the next input (so the same press isn't captured twice)
    if (waitingForRelease_) {
        // We get called with pressed=true, so if mask is nonzero
        // the user is still holding something. But since ProcessButtonMask
        // is only called on press events, just skip one cycle.
        waitingForRelease_ = false;
        isDirty_ = true;
        return;
    }
}

bool ButtonMappingDialog::WriteMappingFile() {
    Path p("root:mapping.xml");
    std::string mapPath = p.GetPath();

    // Ensure parent directory exists
    size_t pos = mapPath.find_last_of('/');
    if (pos != std::string::npos) {
        std::string dir = mapPath.substr(0, pos);
        struct stat st;
        if (stat(dir.c_str(), &st) != 0) {
            mkdir(dir.c_str(), 0755);
        }
    }

    std::ofstream out(mapPath.c_str());
    if (!out) {
        Trace::Error("ButtonMapping: Failed to write %s", mapPath.c_str());
        return false;
    }

    out << "<!-- Button mapping generated by in-app mapper -->\n";
    out << "<MAPPINGS>\n";

    // Always include keyboard fallbacks so the app remains usable
    out << "\n  <!-- Keyboard fallbacks -->\n";
    out << "  <MAP src=\"key:0:up\" dst=\"/event/up\" />\n";
    out << "  <MAP src=\"key:0:down\" dst=\"/event/down\" />\n";
    out << "  <MAP src=\"key:0:left\" dst=\"/event/left\" />\n";
    out << "  <MAP src=\"key:0:right\" dst=\"/event/right\" />\n";
    out << "  <MAP src=\"key:0:s\" dst=\"/event/a\" />\n";
    out << "  <MAP src=\"key:0:a\" dst=\"/event/b\" />\n";
    out << "  <MAP src=\"key:0:q\" dst=\"/event/lshoulder\" />\n";
    out << "  <MAP src=\"key:0:w\" dst=\"/event/rshoulder\" />\n";
    out << "  <MAP src=\"key:0:space\" dst=\"/event/start\" />\n";
    out << "  <MAP src=\"key:0:e\" dst=\"/event/select\" />\n";
    out << "  <MAP src=\"key:0:,\" dst=\"/event/pgback\" />\n";
    out << "  <MAP src=\"key:0:.\" dst=\"/event/pgfwd\" />\n";

    // Write the captured controller mappings
    out << "\n  <!-- Controller mappings (captured) -->\n";
    for (int i = 0; i < MAP_STEP_COUNT; i++) {
        if (!captured_[i].empty()) {
            out << "  <MAP src=\"" << captured_[i]
                << "\" dst=\"" << stepDstUrls_[i] << "\" />\n";
        }
    }

    out << "\n</MAPPINGS>\n";
    out.close();

    
    return true;
}
