#include "ProtonBridge.h"
#include "Application/Model/Config.h"
#include "System/Console/Trace.h"
#include "System/FileSystem/FileSystem.h"

// The FileSystem.h eventually includes TinyXML headers which redefine FILE to
// I_File We need the real system FILE* for popen/pclose, so undefine it here
#ifdef FILE
#undef FILE
#undef fopen
#undef fclose
#undef fread
#endif

#include <algorithm>
#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <sys/resource.h>
#include <sys/stat.h>
#include <unistd.h>
#include <vector>

// Embedded yabridge tar.gz blob (generated by embed_yabridge.sh)
#include "yabridge_blob.h"

// Helper: Parse version number from Proton directory name
static void parseProtonVersion(const std::string &name,
                               ProtonVersion &version) {
    version.name = name;
    version.isExperimental = (name.find("Experimental") != std::string::npos);

    if (version.isExperimental) {
        version.major = version.minor = version.patch = 0;
        return;
    }

    // Parse "Proton X.Y-Z" format
    size_t pos = name.find("Proton ");
    if (pos == std::string::npos) {
        return;
    }

    const char *numStart = name.c_str() + pos + 7; // Skip "Proton "
    char *end = nullptr;
    version.major = (int)strtol(numStart, &end, 10);

    if (end && *end == '.') {
        version.minor = (int)strtol(end + 1, &end, 10);
    }

    if (end && *end == '-') {
        version.patch = (int)strtol(end + 1, &end, 10);
    }
}

// Helper: Check if a wine binary exists at the given path
static bool checkWinePath(const std::string &basePath, const char *subpath,
                          std::string &outWinePath) {
    std::string fullPath = basePath + "/" + subpath;
    struct stat st;
    if (stat(fullPath.c_str(), &st) == 0 && S_ISREG(st.st_mode)) {
        outWinePath = fullPath;
        return true;
    }
    return false;
}

// Discover all available Proton installations
std::vector<ProtonVersion> discoverAllProton(const char *homeDir) {
    std::vector<ProtonVersion> versions;

    std::string steamPath =
        std::string(homeDir) + "/.steam/steam/steamapps/common";
    DIR *dir = opendir(steamPath.c_str());
    if (!dir) {
        Trace::Log("BRIDGE", "Steam directory not found: %s",
                   steamPath.c_str());
        return versions;
    }

    struct dirent *entry;
    while ((entry = readdir(dir)) != nullptr) {
        // Skip . and ..
        if (strcmp(entry->d_name, ".") == 0 ||
            strcmp(entry->d_name, "..") == 0) {
            continue;
        }

        // Check if name contains "Proton"
        if (strstr(entry->d_name, "Proton") == nullptr) {
            continue;
        }

        std::string protonPath = steamPath + "/" + entry->d_name;
        ProtonVersion version;
        parseProtonVersion(entry->d_name, version);

        // Try to find wine binary (newer location first, then older)
        if (checkWinePath(protonPath, "files/bin/wine", version.winePath)) {
            versions.push_back(version);
        } else if (checkWinePath(protonPath, "dist/bin/wine",
                                 version.winePath)) {
            versions.push_back(version);
        }
    }

    closedir(dir);

    // Sort: Experimental first, then by version descending
    std::sort(versions.begin(), versions.end(),
              [](const ProtonVersion &a, const ProtonVersion &b) {
                  if (a.isExperimental != b.isExperimental) {
                      return a.isExperimental; // Experimental comes first
                  }
                  if (a.major != b.major)
                      return a.major > b.major;
                  if (a.minor != b.minor)
                      return a.minor > b.minor;
                  return a.patch > b.patch;
              });

    // Log discovered versions
    Trace::Log("BRIDGE", "Found %d Proton installation(s)",
               (int)versions.size());
    for (size_t i = 0; i < versions.size(); i++) {
        Trace::Log("BRIDGE", "  [%d] %s -> %s", (int)i,
                   versions[i].name.c_str(), versions[i].winePath.c_str());
    }

    return versions;
}

// Find the best Proton wine binary path
std::string findProtonWine(const char *homeDir) {
    // Check for user preference in config
    const char *preferredVersion =
        Config::GetInstance()->GetValue("PROTONVERSION");

    std::vector<ProtonVersion> versions = discoverAllProton(homeDir);
    if (versions.empty()) {
        return "";
    }

    // If user specified a preference, try to find it
    if (preferredVersion && preferredVersion[0] != '\0') {
        for (const auto &v : versions) {
            if (v.name.find(preferredVersion) != std::string::npos) {
                Trace::Log("BRIDGE", "Using preferred Proton: %s",
                           v.name.c_str());
                return v.winePath;
            }
        }
        Trace::Log(
            "BRIDGE",
            "Preferred Proton '%s' not found, using auto-selected version",
            preferredVersion);
    }

    // Return the best (first) version
    Trace::Log("BRIDGE", "Auto-selected Proton: %s", versions[0].name.c_str());
    return versions[0].winePath;
}

// Extract the embedded yabridge tar.gz blob into ~/Documents/SDTracker/yabridge/.
// This keeps yabridge alongside the other app data (projects, samplelib, themes).
// Returns true if yabridge/ already exists or was successfully extracted.
static bool extractEmbeddedYabridge(const char *home) {
    std::string sdtDir = std::string(home) + "/Documents/SDTracker";
    std::string yabridgeDir = sdtDir + "/yabridge";
    std::string yabridgectlBin = yabridgeDir + "/yabridgectl";

    // Already extracted?
    struct stat st;
    if (stat(yabridgectlBin.c_str(), &st) == 0 && S_ISREG(st.st_mode)) {
        Trace::Log("BRIDGE", "yabridge already present at %s",
                   yabridgeDir.c_str());
        return true;
    }

    Trace::Log("BRIDGE",
               "yabridge not found, extracting embedded archive (%u bytes)...",
               yabridge_blob_len);

    // Ensure the SDTracker directory exists
    if (stat(sdtDir.c_str(), &st) != 0) {
        mkdir(sdtDir.c_str(), 0755);
    }

    // Write the embedded tar.gz to a temporary file
    char tmpPath[] = "/tmp/yabridge_embed_XXXXXX";
    int fd = mkstemp(tmpPath);
    if (fd < 0) {
        Trace::Log("BRIDGE", "Failed to create temp file for extraction");
        return false;
    }

    ssize_t written = 0;
    const unsigned char *ptr = yabridge_blob;
    unsigned int remaining = yabridge_blob_len;
    while (remaining > 0) {
        ssize_t w = write(fd, ptr, remaining);
        if (w <= 0) {
            Trace::Log("BRIDGE", "Failed to write embedded blob to temp file");
            close(fd);
            unlink(tmpPath);
            return false;
        }
        ptr += w;
        remaining -= (unsigned int)w;
        written += w;
    }
    close(fd);

    Trace::Log("BRIDGE", "Wrote %d bytes to %s", (int)written, tmpPath);

    // Extract tar.gz into ~/Documents/SDTracker/
    // The archive contains a top-level yabridge/ directory
    std::string extractCmd = "tar xzf \"" + std::string(tmpPath) + "\" -C \"" +
                             sdtDir + "\" 2>&1";
    Trace::Log("BRIDGE", "Extracting: %s", extractCmd.c_str());

    FILE *pipe = popen(extractCmd.c_str(), "r");
    if (pipe) {
        char line[256];
        while (fgets(line, sizeof(line), pipe)) {
            size_t len = strlen(line);
            if (len > 0 && line[len - 1] == '\n')
                line[len - 1] = '\0';
            Trace::Log("BRIDGE", "  %s", line);
        }
        int result = pclose(pipe);
        unlink(tmpPath);

        if (result != 0) {
            Trace::Log("BRIDGE", "tar extraction failed with code %d", result);
            return false;
        }
    } else {
        Trace::Log("BRIDGE", "Failed to run tar for extraction");
        unlink(tmpPath);
        return false;
    }

    // Ensure all binaries are executable
    const char *exeFiles[] = {"yabridgectl",
                              "yabridge-host.exe",
                              "yabridge-host.exe.so",
                              "yabridge-host-32.exe",
                              "yabridge-host-32.exe.so"};
    for (size_t i = 0; i < sizeof(exeFiles) / sizeof(exeFiles[0]); i++) {
        std::string path = yabridgeDir + "/" + exeFiles[i];
        chmod(path.c_str(), 0755);
    }

    // Verify extraction succeeded
    if (stat(yabridgectlBin.c_str(), &st) == 0 && S_ISREG(st.st_mode)) {
        Trace::Log("BRIDGE", "yabridge extracted successfully to %s",
                   yabridgeDir.c_str());
        return true;
    }

    Trace::Log("BRIDGE", "Extraction appeared to succeed but yabridgectl not "
                         "found at %s",
               yabridgectlBin.c_str());
    return false;
}

// After yabridgectl sync, propagate moduleinfo.json from the original
// Windows .vst3 bundles in ~/.vst3/win/ to the bridged Linux bundles in
// ~/.vst3/yabridge/. This lets the scanner enumerate bridged plugins
// without dlopen'ing them (which triggers the chainloader + Wine).
// For Windows bundles that lack moduleinfo.json, a minimal stub is
// generated from the filename so the plugin at least appears in the browser.
static void propagateModuleInfo(const char *home,
                                const std::string &winDir) {
    std::string bridgedDir = std::string(home) + "/.vst3/yabridge";
    DIR *dir = opendir(bridgedDir.c_str());
    if (!dir)
        return;

    struct dirent *entry;
    while ((entry = readdir(dir)) != nullptr) {
        // Look for .vst3 bundles (directories ending in .vst3)
        const char *ext = strstr(entry->d_name, ".vst3");
        if (!ext || ext[5] != '\0')
            continue;

        std::string bridgedBundle = bridgedDir + "/" + entry->d_name;
        std::string bridgedJson =
            bridgedBundle + "/Contents/moduleinfo.json";

        // Already has moduleinfo.json?
        struct stat st;
        if (stat(bridgedJson.c_str(), &st) == 0 && st.st_size > 0)
            continue;

        // Try to copy from the original Windows bundle
        std::string winBundle = winDir + "/" + entry->d_name;
        std::string winJson = winBundle + "/Contents/moduleinfo.json";

        bool copied = false;
        if (stat(winJson.c_str(), &st) == 0 && st.st_size > 0) {
            FILE *src = fopen(winJson.c_str(), "r");
            if (src) {
                std::string content;
                content.resize(st.st_size);
                size_t nread = fread(&content[0], 1, st.st_size, src);
                fclose(src);

                if ((off_t)nread == st.st_size) {
                    std::string contentsDir = bridgedBundle + "/Contents";
                    mkdir(contentsDir.c_str(), 0755);

                    FILE *dst = fopen(bridgedJson.c_str(), "w");
                    if (dst) {
                        fwrite(content.c_str(), 1, content.size(), dst);
                        fclose(dst);
                        copied = true;
                        Trace::Log("BRIDGE",
                                   "Copied moduleinfo.json for %s",
                                   entry->d_name);
                    }
                }
            }
        }

        // No moduleinfo.json in original Windows bundle either — generate a
        // minimal stub so the scanner can at least show the plugin name.
        // CID is zeroed; loadPlugin() resolves the real CID from the factory.
        if (!copied) {
            std::string pluginName = entry->d_name;
            size_t dotPos = pluginName.rfind(".vst3");
            if (dotPos != std::string::npos)
                pluginName = pluginName.substr(0, dotPos);

            std::string contentsDir = bridgedBundle + "/Contents";
            mkdir(contentsDir.c_str(), 0755);

            std::string json;
            json += "{\n";
            json += "  \"Classes\": [\n";
            json += "    {\n";
            json +=
                "      \"CID\": "
                "\"00000000000000000000000000000000\",\n";
            json += "      \"Category\": \"Audio Module Class\",\n";
            json += "      \"Name\": \"" + pluginName + "\",\n";
            json += "      \"Sub Categories\": \"\"\n";
            json += "    }\n";
            json += "  ]\n";
            json += "}\n";

            FILE *dst = fopen(bridgedJson.c_str(), "w");
            if (dst) {
                fwrite(json.c_str(), 1, json.size(), dst);
                fclose(dst);
                Trace::Log("BRIDGE",
                           "Generated moduleinfo.json stub for %s "
                           "(name=%s)",
                           entry->d_name, pluginName.c_str());
            }
        }
    }
    closedir(dir);
}

// Main entry point: bridge Windows VST3 plugins using yabridge + Proton
void bridgeWindowsVST3s() {
    // Get HOME environment variable
    const char *home = getenv("HOME");
    if (!home) {
        Trace::Log(
            "BRIDGE",
            "HOME environment variable not set, skipping Windows VST3 bridge");
        return;
    }

    // Raise the memory-locking limit.  Wine/yabridge need to mlock pages
    // for real-time audio.  The Steam Deck default is only 64 KB which
    // causes "low memory locking limit" warnings and audio silence.
    {
        struct rlimit rl;
        if (getrlimit(RLIMIT_MEMLOCK, &rl) == 0) {
            Trace::Log("BRIDGE", "Current RLIMIT_MEMLOCK: soft=%lu hard=%lu",
                       (unsigned long)rl.rlim_cur,
                       (unsigned long)rl.rlim_max);
            if (rl.rlim_cur < rl.rlim_max) {
                rl.rlim_cur = rl.rlim_max;
                if (setrlimit(RLIMIT_MEMLOCK, &rl) == 0) {
                    Trace::Log("BRIDGE",
                               "Raised RLIMIT_MEMLOCK soft to %lu",
                               (unsigned long)rl.rlim_cur);
                }
            }
            // If hard limit is also too low (< 256 MB), try unlimited.
            // This will only succeed if we have CAP_SYS_RESOURCE or
            // the user configured /etc/security/limits.d.
            if (rl.rlim_cur != RLIM_INFINITY && rl.rlim_cur < 256u * 1024 * 1024) {
                struct rlimit unlim;
                unlim.rlim_cur = RLIM_INFINITY;
                unlim.rlim_max = RLIM_INFINITY;
                if (setrlimit(RLIMIT_MEMLOCK, &unlim) == 0) {
                    Trace::Log("BRIDGE",
                               "Set RLIMIT_MEMLOCK to unlimited");
                } else {
                    Trace::Log("BRIDGE",
                               "WARNING: Could not raise memlock limit "
                               "above %lu — Wine may print warnings. "
                               "Add a /etc/security/limits.d/ entry for "
                               "unlimited memlock if audio doesn't work.",
                               (unsigned long)rl.rlim_cur);
                }
            }
        }
    }

    // Create ~/.vst3/win/ directory if it doesn't exist
    std::string vst3WinDir = std::string(home) + "/.vst3/win";
    struct stat st;
    if (stat(vst3WinDir.c_str(), &st) != 0) {
        // Create parent directory first if needed
        std::string vst3Dir = std::string(home) + "/.vst3";
        if (stat(vst3Dir.c_str(), &st) != 0) {
            if (mkdir(vst3Dir.c_str(), 0755) != 0) {
                Trace::Log("BRIDGE", "Failed to create ~/.vst3 directory");
                return;
            }
        }
        if (mkdir(vst3WinDir.c_str(), 0755) != 0) {
            Trace::Log("BRIDGE", "Failed to create ~/.vst3/win directory");
            return;
        }
        Trace::Log("BRIDGE", "Created %s for Windows VST3 files",
                   vst3WinDir.c_str());
    }

    // Find Proton wine binary
    std::string winePath = findProtonWine(home);
    if (winePath.empty()) {
        Trace::Log(
            "BRIDGE",
            "No Proton installation found, skipping Windows VST3 bridge");
        return;
    }

    // Export WINELOADER so that the yabridge chainloader (triggered by dlopen
    // when the user actually loads a bridged plugin) can find Wine/Proton.
    setenv("WINELOADER", winePath.c_str(), 1);
    Trace::Log("BRIDGE", "Set WINELOADER=%s", winePath.c_str());

    // Proton's wine binary links against libs in its own files/lib{,64}.
    // Without these on LD_LIBRARY_PATH the binary (and yabridge-host.exe)
    // will fail to resolve symbols at runtime on a stock Steam Deck.
    // We derive the Proton base from the wine path:
    //   .../Proton X.Y/files/bin/wine  ->  .../Proton X.Y
    std::string protonBase;
    {
        // winePath = .../files/bin/wine  or  .../dist/bin/wine
        std::string tmp = winePath;
        // Strip "/wine"
        size_t sl = tmp.rfind('/');
        if (sl != std::string::npos) tmp = tmp.substr(0, sl);
        // Strip "/bin"
        sl = tmp.rfind('/');
        if (sl != std::string::npos) tmp = tmp.substr(0, sl);
        // Strip "/files" or "/dist"
        sl = tmp.rfind('/');
        if (sl != std::string::npos) tmp = tmp.substr(0, sl);
        protonBase = tmp;
    }

    // Build LD_LIBRARY_PATH additions from Proton's lib directories
    {
        // Determine which sub-tree the wine binary is in (files/ or dist/)
        std::string subTree;
        if (winePath.find("/files/bin/") != std::string::npos)
            subTree = protonBase + "/files";
        else
            subTree = protonBase + "/dist";

        std::string libDirs = subTree + "/lib:" + subTree + "/lib64";

        const char *existing = getenv("LD_LIBRARY_PATH");
        std::string newLdPath = libDirs;
        if (existing && existing[0] != '\0') {
            newLdPath += ":";
            newLdPath += existing;
        }
        setenv("LD_LIBRARY_PATH", newLdPath.c_str(), 1);
        Trace::Log("BRIDGE", "Set LD_LIBRARY_PATH=%s", newLdPath.c_str());
    }

    // Also put the yabridge directory on PATH so the chainloader can
    // find yabridge-host.exe (it's a winelib app that the bridge
    // library spawns via execvp).
    {
        std::string yabDir =
            std::string(home) + "/Documents/SDTracker/yabridge";
        const char *existingPath = getenv("PATH");
        std::string newPath = yabDir;
        if (existingPath && existingPath[0] != '\0') {
            newPath += ":";
            newPath += existingPath;
        }
        setenv("PATH", newPath.c_str(), 1);
        Trace::Log("BRIDGE", "Prepended yabridge to PATH");
    }

    // Set up a dedicated WINEPREFIX for yabridge.  Without this the Wine
    // host process falls back to ~/.wine which usually doesn't exist on a
    // Steam Deck.  We keep the prefix alongside our other app data.
    std::string winePrefix =
        std::string(home) + "/Documents/SDTracker/wineprefix";
    setenv("WINEPREFIX", winePrefix.c_str(), 1);
    setenv("WINEFSYNC", "1", 0); // enable fsync if available (don't override)
    Trace::Log("BRIDGE", "Set WINEPREFIX=%s", winePrefix.c_str());

    // Initialise the prefix if it doesn't exist yet.
    // Prefer using the Proton `proton` script which handles all the
    // internal Wine environment setup (library paths, registry, etc.).
    // Fall back to calling wineboot directly for non-Proton Wine.
    {
        struct stat pfxSt;
        bool needsBoot = false;
        if (stat(winePrefix.c_str(), &pfxSt) != 0) {
            needsBoot = true;
        } else {
            // Prefix directory exists — check for system.reg as a
            // quick "is it actually initialised?" test.
            std::string sysReg = winePrefix + "/system.reg";
            if (stat(sysReg.c_str(), &pfxSt) != 0)
                needsBoot = true;
        }

        if (needsBoot) {
            std::string bootCmd;
            std::string protonScript = protonBase + "/proton";
            struct stat psSt;

            if (stat(protonScript.c_str(), &psSt) == 0 &&
                S_ISREG(psSt.st_mode)) {
                // Use the Proton script — it sets up its own environment.
                // STEAM_COMPAT_DATA_PATH tells Proton where to put the pfx/.
                // We point it at our prefix parent so Proton creates pfx/
                // inside it; then we symlink to make WINEPREFIX work too.
                std::string compatData = winePrefix;
                bootCmd =
                    "STEAM_COMPAT_DATA_PATH=\"" + compatData +
                    "\" STEAM_COMPAT_CLIENT_INSTALL_PATH=\"" +
                    std::string(home) + "/.steam/steam"
                    "\" DISPLAY= WAYLAND_DISPLAY="
                    " python3 \"" + protonScript + "\" run wineboot -u 2>&1";
            } else {
                // Non-Proton Wine: call wineboot directly
                std::string wineDir = winePath;
                size_t slashPos = wineDir.rfind('/');
                if (slashPos != std::string::npos)
                    wineDir = wineDir.substr(0, slashPos);
                std::string wineboot = wineDir + "/wineboot";

                struct stat wbSt;
                if (stat(wineboot.c_str(), &wbSt) != 0)
                    wineboot = "wineboot";

                bootCmd = "WINELOADER=\"" + winePath +
                          "\" WINEPREFIX=\"" + winePrefix +
                          "\" WINEFSYNC=1"
                          " DISPLAY= WAYLAND_DISPLAY="
                          " \"" + wineboot + "\" -u 2>&1";
            }

            Trace::Log("BRIDGE", "Initialising Wine prefix: %s",
                       bootCmd.c_str());

            FILE *bootPipe = popen(bootCmd.c_str(), "r");
            if (bootPipe) {
                char line[256];
                while (fgets(line, sizeof(line), bootPipe)) {
                    size_t len = strlen(line);
                    if (len > 0 && line[len - 1] == '\n')
                        line[len - 1] = '\0';
                    Trace::Log("BRIDGE", "  %s", line);
                }
                int bootResult = pclose(bootPipe);
                if (bootResult == 0) {
                    Trace::Log("BRIDGE",
                               "Wine prefix initialised successfully");
                } else {
                    Trace::Log("BRIDGE",
                               "wineboot returned code %d (may still work)",
                               bootResult);
                }
            } else {
                Trace::Log("BRIDGE", "WARNING: Failed to run wineboot");
            }

            // Proton creates the prefix inside pfx/ under the compat data
            // path.  Make sure WINEPREFIX points to where the files actually
            // are.  If proton created <winePrefix>/pfx/ with the real prefix,
            // redirect WINEPREFIX to it.
            std::string pfxSub = winePrefix + "/pfx";
            std::string pfxSysReg = pfxSub + "/system.reg";
            if (stat(pfxSysReg.c_str(), &pfxSt) == 0) {
                winePrefix = pfxSub;
                setenv("WINEPREFIX", winePrefix.c_str(), 1);
                Trace::Log("BRIDGE",
                           "Proton created prefix in pfx/ — updated "
                           "WINEPREFIX=%s",
                           winePrefix.c_str());
            }
        }
    }

    // Copy essential DLLs that Proton's default prefix ships but that our
    // wineboot-created prefix may be missing.  In particular libvkd3d-1.dll
    // and libvkd3d-shader-1.dll are required by wined3d.dll → dxgi.dll
    // which many Windows VST3 plugins link against for their GUI.
    {
        std::string defaultPfx = protonBase + "/files/share/default_pfx";
        const char *dllNames[] = {
            "libvkd3d-1.dll",
            "libvkd3d-shader-1.dll",
        };
        const char *subdirs[] = { "system32", "syswow64" };
        for (size_t s = 0; s < sizeof(subdirs) / sizeof(subdirs[0]); s++) {
            std::string ourDir  = winePrefix + "/drive_c/windows/" + subdirs[s];
            std::string srcDir  = defaultPfx + "/drive_c/windows/" + subdirs[s];
            struct stat dirSt;
            if (stat(ourDir.c_str(), &dirSt) != 0) continue; // subdir doesn't exist
            for (size_t d = 0; d < sizeof(dllNames) / sizeof(dllNames[0]); d++) {
                std::string dst = ourDir  + "/" + dllNames[d];
                std::string src = srcDir  + "/" + dllNames[d];
                struct stat dstSt, srcSt;
                if (stat(dst.c_str(), &dstSt) == 0) continue; // already present
                if (stat(src.c_str(), &srcSt) != 0) continue; // source missing
                FILE *sf = fopen(src.c_str(), "rb");
                if (!sf) continue;
                FILE *df = fopen(dst.c_str(), "wb");
                if (!df) { fclose(sf); continue; }
                char cpBuf[8192];
                size_t n;
                while ((n = fread(cpBuf, 1, sizeof(cpBuf), sf)) > 0)
                    fwrite(cpBuf, 1, n, df);
                fclose(sf); fclose(df);
                chmod(dst.c_str(), 0755);
                Trace::Log("BRIDGE", "Copied %s/%s from Proton default prefix",
                           subdirs[s], dllNames[d]);
            }
        }
    }

    // Extract embedded yabridge into ~/Documents/SDTracker/yabridge/ if needed
    extractEmbeddedYabridge(home);

    // Locate yabridge yabridgectl binary
    // Look in root: (~/Documents/SDTracker/) first, then fall back to bin:
    const char *candidates[] = {"root:yabridge/yabridgectl",
                                "bin:yabridge/yabridgectl",
                                "bin:../yabridge/yabridgectl"};

    Path yabridgectlPath;
    bool found = false;
    for (size_t i = 0; i < sizeof(candidates) / sizeof(candidates[0]); i++) {
        Path candidate(candidates[i]);
        if (FileSystem::GetInstance()->GetFileType(
                candidate.GetPath().c_str()) == FT_FILE) {
            yabridgectlPath = candidate;
            found = true;
            break;
        }
    }

    if (!found) {
        Trace::Log("BRIDGE",
                   "yabridge not bundled, skipping Windows VST3 bridge");
        return;
    }

    std::string yabridgectlBin = yabridgectlPath.GetCanonicalPath();
    Trace::Log("BRIDGE", "Found yabridgectl: %s", yabridgectlBin.c_str());

    // Derive the yabridge lib directory (same dir as yabridgectl)
    std::string yabridgeLibDir = yabridgectlBin;
    size_t lastSlashPos = yabridgeLibDir.rfind('/');
    if (lastSlashPos != std::string::npos) {
        yabridgeLibDir = yabridgeLibDir.substr(0, lastSlashPos);
    }

    // Write yabridgectl config so it knows where our bundled .so files are.
    // The CLI `yabridgectl set --path` crashes in yabridge 5.1.1 so we write
    // the config TOML directly to ~/.config/yabridgectl/config.toml
    std::string configDir = std::string(home) + "/.config/yabridgectl";
    std::string configPath = configDir + "/" + "config.toml";
    struct stat cfgSt;
    if (stat(configDir.c_str(), &cfgSt) != 0) {
        std::string mkdirCmd =
            "mkdir -p \"" + configDir + "\"";
        (void)system(mkdirCmd.c_str());
    }

    // Read existing config to preserve user settings, but always update path
    // and ensure our plugin_dirs entry is present
    {
        std::string toml;
        toml += "yabridge_home = '" + yabridgeLibDir + "'\n";
        toml += "plugin_dirs = ['" + vst3WinDir + "']\n";
        toml += "vst2_location = 'centralized'\n";
        toml += "no_verify = false\n";
        toml += "blacklist = []\n";

        FILE *cfgFile = fopen(configPath.c_str(), "w");
        if (cfgFile) {
            fwrite(toml.c_str(), 1, toml.size(), cfgFile);
            fclose(cfgFile);
            Trace::Log("BRIDGE", "Wrote yabridgectl config: path = '%s'",
                       yabridgeLibDir.c_str());
        } else {
            Trace::Log("BRIDGE",
                       "WARNING: Could not write yabridgectl config to %s",
                       configPath.c_str());
        }
    }

    // Create ~/.local/share/yabridge symlink pointing to our bundled directory.
    // The yabridge chainloader .so inside bridged plugins searches for
    // libyabridge-vst3.so (and yabridge-host.exe) in $PATH and
    // ~/.local/share/yabridge/. Without this symlink the chainloader can't find
    // the actual bridge library at runtime.
    {
        std::string shareDir = std::string(home) + "/.local/share";
        std::string symlinkPath = shareDir + "/yabridge";

        // Create ~/.local/share if needed
        struct stat shareSt;
        if (stat(shareDir.c_str(), &shareSt) != 0) {
            std::string mkShareCmd = "mkdir -p \"" + shareDir + "\"";
            (void)system(mkShareCmd.c_str());
        }

        // Check if symlink already points to the right place
        char linkTarget[1024];
        ssize_t linkLen =
            readlink(symlinkPath.c_str(), linkTarget, sizeof(linkTarget) - 1);
        bool needSymlink = true;
        if (linkLen > 0) {
            linkTarget[linkLen] = '\0';
            if (std::string(linkTarget) == yabridgeLibDir) {
                needSymlink = false;
            } else {
                // Symlink exists but points elsewhere — remove it
                unlink(symlinkPath.c_str());
            }
        } else {
            // If it's a regular directory (not a symlink), leave it alone
            struct stat linkSt;
            if (lstat(symlinkPath.c_str(), &linkSt) == 0 &&
                S_ISDIR(linkSt.st_mode)) {
                Trace::Log("BRIDGE",
                           "%s is a real directory, not overwriting",
                           symlinkPath.c_str());
                needSymlink = false;
            }
        }

        if (needSymlink) {
            if (symlink(yabridgeLibDir.c_str(), symlinkPath.c_str()) == 0) {
                Trace::Log("BRIDGE", "Created symlink %s -> %s",
                           symlinkPath.c_str(), yabridgeLibDir.c_str());
            } else {
                Trace::Log("BRIDGE", "WARNING: Failed to create symlink %s",
                           symlinkPath.c_str());
            }
        }
    }

    // Run yabridgectl add "~/.vst3/win/"
    std::string addCmd =
        "\"" + yabridgectlBin + "\" add \"" + vst3WinDir + "\" 2>&1";
    Trace::Log("BRIDGE", "Running: %s", addCmd.c_str());

    FILE *addPipe = popen(addCmd.c_str(), "r");
    if (addPipe) {
        char line[256];
        while (fgets(line, sizeof(line), addPipe)) {
            // Strip trailing newline
            size_t len = strlen(line);
            if (len > 0 && line[len - 1] == '\n') {
                line[len - 1] = '\0';
            }
            Trace::Log("BRIDGE", "  %s", line);
        }
        int addResult = pclose(addPipe);
        if (addResult != 0) {
            Trace::Log("BRIDGE", "yabridgectl add failed with code %d",
                       addResult);
        }
    } else {
        Trace::Log("BRIDGE", "Failed to run yabridgectl add");
        return;
    }

    // Run WINELOADER="..." yabridgectl sync
    std::string syncCmd =
        "WINELOADER=\"" + winePath + "\" \"" + yabridgectlBin + "\" sync 2>&1";
    Trace::Log("BRIDGE", "Running: %s", syncCmd.c_str());

    FILE *syncPipe = popen(syncCmd.c_str(), "r");
    if (syncPipe) {
        char line[256];
        while (fgets(line, sizeof(line), syncPipe)) {
            // Strip trailing newline
            size_t len = strlen(line);
            if (len > 0 && line[len - 1] == '\n') {
                line[len - 1] = '\0';
            }
            Trace::Log("BRIDGE", "  %s", line);
        }
        int syncResult = pclose(syncPipe);
        if (syncResult == 0) {
            Trace::Log("BRIDGE",
                       "Windows VST3 bridge setup completed successfully");

            // Propagate / generate moduleinfo.json so the scanner can
            // enumerate bridged plugins without dlopen'ing them.
            propagateModuleInfo(home, vst3WinDir);
        } else {
            Trace::Log("BRIDGE", "yabridgectl sync failed with code %d",
                       syncResult);
        }
    } else {
        Trace::Log("BRIDGE", "Failed to run yabridgectl sync");
    }
}
