#include "ProtonBridge.h"
#include "Application/Model/Config.h"
#include "System/Console/Trace.h"
#include "System/FileSystem/FileSystem.h"

// The FileSystem.h eventually includes TinyXML headers which redefine FILE to
// I_File We need the real system FILE* for popen/pclose, so undefine it here
#ifdef FILE
#undef FILE
#undef fopen
#undef fclose
#undef fread
#endif

#include <algorithm>
#include <dirent.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <sys/resource.h>
#include <sys/stat.h>
#include <unistd.h>
#include <vector>

// Embedded yabridge tar.gz blob (generated by embed_yabridge.sh)
#include "yabridge_blob.h"

// Helper: Parse version number from Proton directory name
static void parseProtonVersion(const std::string &name,
                               ProtonVersion &version) {
    version.name = name;
    version.isExperimental = (name.find("Experimental") != std::string::npos);

    if (version.isExperimental) {
        version.major = version.minor = version.patch = 0;
        return;
    }

    // Parse "Proton X.Y-Z" format
    size_t pos = name.find("Proton ");
    if (pos == std::string::npos) {
        return;
    }

    const char *numStart = name.c_str() + pos + 7; // Skip "Proton "
    char *end = nullptr;
    version.major = (int)strtol(numStart, &end, 10);

    if (end && *end == '.') {
        version.minor = (int)strtol(end + 1, &end, 10);
    }

    if (end && *end == '-') {
        version.patch = (int)strtol(end + 1, &end, 10);
    }
}

// Helper: Check if a wine binary exists at the given path
static bool checkWinePath(const std::string &basePath, const char *subpath,
                          std::string &outWinePath) {
    std::string fullPath = basePath + "/" + subpath;
    struct stat st;
    if (stat(fullPath.c_str(), &st) == 0 && S_ISREG(st.st_mode)) {
        outWinePath = fullPath;
        return true;
    }
    return false;
}

// Discover all available Proton installations
std::vector<ProtonVersion> discoverAllProton(const char *homeDir) {
    std::vector<ProtonVersion> versions;

    std::string steamPath =
        std::string(homeDir) + "/.steam/steam/steamapps/common";
    DIR *dir = opendir(steamPath.c_str());
    if (!dir)
        return versions;

    struct dirent *entry;
    while ((entry = readdir(dir)) != nullptr) {
        // Skip . and ..
        if (strcmp(entry->d_name, ".") == 0 ||
            strcmp(entry->d_name, "..") == 0) {
            continue;
        }

        // Check if name contains "Proton"
        if (strstr(entry->d_name, "Proton") == nullptr) {
            continue;
        }

        std::string protonPath = steamPath + "/" + entry->d_name;
        ProtonVersion version;
        parseProtonVersion(entry->d_name, version);

        // Try to find wine binary (newer location first, then older)
        if (checkWinePath(protonPath, "files/bin/wine", version.winePath)) {
            versions.push_back(version);
        } else if (checkWinePath(protonPath, "dist/bin/wine",
                                 version.winePath)) {
            versions.push_back(version);
        }
    }

    closedir(dir);

    // Sort: Experimental first, then by version descending
    std::sort(versions.begin(), versions.end(),
              [](const ProtonVersion &a, const ProtonVersion &b) {
                  if (a.isExperimental != b.isExperimental) {
                      return a.isExperimental; // Experimental comes first
                  }
                  if (a.major != b.major)
                      return a.major > b.major;
                  if (a.minor != b.minor)
                      return a.minor > b.minor;
                  return a.patch > b.patch;
              });

    return versions;
}

// Find the best Proton wine binary path
std::string findProtonWine(const char *homeDir) {
    // Check for user preference in config
    const char *preferredVersion =
        Config::GetInstance()->GetValue("PROTONVERSION");

    std::vector<ProtonVersion> versions = discoverAllProton(homeDir);
    if (versions.empty()) {
        return "";
    }

    // If user specified a preference, try to find it
    if (preferredVersion && preferredVersion[0] != '\0') {
        for (const auto &v : versions) {
            if (v.name.find(preferredVersion) != std::string::npos)
                return v.winePath;
        }
    }

    return versions[0].winePath;
}

// Extract the embedded yabridge tar.gz blob into ~/Documents/SDTracker/yabridge/.
// This keeps yabridge alongside the other app data (projects, samplelib, themes).
// Returns true if yabridge/ already exists or was successfully extracted.
static bool extractEmbeddedYabridge(const char *home) {
    std::string sdtDir = std::string(home) + "/Documents/SDTracker";
    std::string yabridgeDir = sdtDir + "/yabridge";
    std::string yabridgectlBin = yabridgeDir + "/yabridgectl";

    // Already extracted?
    struct stat st;
    if (stat(yabridgectlBin.c_str(), &st) == 0 && S_ISREG(st.st_mode))
        return true;

    // Ensure the SDTracker directory exists
    if (stat(sdtDir.c_str(), &st) != 0) {
        mkdir(sdtDir.c_str(), 0755);
    }

    // Write the embedded tar.gz to a temporary file
    char tmpPath[] = "/tmp/yabridge_embed_XXXXXX";
    int fd = mkstemp(tmpPath);
    if (fd < 0)
        return false;

    ssize_t written = 0;
    const unsigned char *ptr = yabridge_blob;
    unsigned int remaining = yabridge_blob_len;
    while (remaining > 0) {
        ssize_t w = write(fd, ptr, remaining);
        if (w <= 0) {
            close(fd);
            unlink(tmpPath);
            return false;
        }
        ptr += w;
        remaining -= (unsigned int)w;
        written += w;
    }
    close(fd);

    std::string extractCmd = "tar xzf \"" + std::string(tmpPath) + "\" -C \"" +
                             sdtDir + "\" 2>&1";
    FILE *pipe = popen(extractCmd.c_str(), "r");
    if (pipe) {
        char line[256];
        while (fgets(line, sizeof(line), pipe)) {}
        int result = pclose(pipe);
        unlink(tmpPath);
        if (result != 0)
            return false;
    } else {
        unlink(tmpPath);
        return false;
    }

    // Ensure all binaries are executable
    const char *exeFiles[] = {"yabridgectl",
                              "yabridge-host.exe",
                              "yabridge-host.exe.so",
                              "yabridge-host-32.exe",
                              "yabridge-host-32.exe.so"};
    for (size_t i = 0; i < sizeof(exeFiles) / sizeof(exeFiles[0]); i++) {
        std::string path = yabridgeDir + "/" + exeFiles[i];
        chmod(path.c_str(), 0755);
    }

    // Verify extraction succeeded
    if (stat(yabridgectlBin.c_str(), &st) == 0 && S_ISREG(st.st_mode))
        return true;

    return false;
}

// After yabridgectl sync, propagate moduleinfo.json from the original
// Windows .vst3 bundles in ~/.vst3/win/ to the bridged Linux bundles in
// ~/.vst3/yabridge/. This lets the scanner enumerate bridged plugins
// without dlopen'ing them (which triggers the chainloader + Wine).
// For Windows bundles that lack moduleinfo.json, a minimal stub is
// generated from the filename so the plugin at least appears in the browser.
static void propagateModuleInfo(const char *home,
                                const std::string &winDir) {
    std::string bridgedDir = std::string(home) + "/.vst3/yabridge";
    DIR *dir = opendir(bridgedDir.c_str());
    if (!dir)
        return;

    struct dirent *entry;
    while ((entry = readdir(dir)) != nullptr) {
        // Look for .vst3 bundles (directories ending in .vst3)
        const char *ext = strstr(entry->d_name, ".vst3");
        if (!ext || ext[5] != '\0')
            continue;

        std::string bridgedBundle = bridgedDir + "/" + entry->d_name;
        std::string bridgedJson =
            bridgedBundle + "/Contents/moduleinfo.json";

        // Already has moduleinfo.json?
        struct stat st;
        if (stat(bridgedJson.c_str(), &st) == 0 && st.st_size > 0)
            continue;

        // Try to copy from the original Windows bundle
        std::string winBundle = winDir + "/" + entry->d_name;
        std::string winJson = winBundle + "/Contents/moduleinfo.json";

        bool copied = false;
        if (stat(winJson.c_str(), &st) == 0 && st.st_size > 0) {
            FILE *src = fopen(winJson.c_str(), "r");
            if (src) {
                std::string content;
                content.resize(st.st_size);
                size_t nread = fread(&content[0], 1, st.st_size, src);
                fclose(src);

                if ((off_t)nread == st.st_size) {
                    std::string contentsDir = bridgedBundle + "/Contents";
                    mkdir(contentsDir.c_str(), 0755);

                    FILE *dst = fopen(bridgedJson.c_str(), "w");
                    if (dst) {
                        fwrite(content.c_str(), 1, content.size(), dst);
                        fclose(dst);
                        copied = true;
                    }
                }
            }
        }

        // No moduleinfo.json in original Windows bundle either — generate a
        // minimal stub so the scanner can at least show the plugin name.
        // CID is zeroed; loadPlugin() resolves the real CID from the factory.
        if (!copied) {
            std::string pluginName = entry->d_name;
            size_t dotPos = pluginName.rfind(".vst3");
            if (dotPos != std::string::npos)
                pluginName = pluginName.substr(0, dotPos);

            std::string contentsDir = bridgedBundle + "/Contents";
            mkdir(contentsDir.c_str(), 0755);

            std::string json;
            json += "{\n";
            json += "  \"Classes\": [\n";
            json += "    {\n";
            json +=
                "      \"CID\": "
                "\"00000000000000000000000000000000\",\n";
            json += "      \"Category\": \"Audio Module Class\",\n";
            json += "      \"Name\": \"" + pluginName + "\",\n";
            json += "      \"Sub Categories\": \"\"\n";
            json += "    }\n";
            json += "  ]\n";
            json += "}\n";

            FILE *dst = fopen(bridgedJson.c_str(), "w");
            if (dst) {
                fwrite(json.c_str(), 1, json.size(), dst);
                fclose(dst);
            }
        }
    }
    closedir(dir);
}

// Main entry point: bridge Windows VST3 plugins using yabridge + Proton
void bridgeWindowsVST3s() {
    // Get HOME environment variable
    const char *home = getenv("HOME");
    if (!home)
        return;

    // ---- Strip Steam's gameoverlayrenderer from LD_PRELOAD ----
    // In game mode Steam injects its 32-bit overlay via LD_PRELOAD.
    // That causes "wrong ELF class: ELFCLASS32" on every 64-bit
    // dlopen (yabridge-host, Wine, etc.) and may prevent the Wine
    // host from starting at all for large plugins like Serum 2.
    {
        const char *preload = getenv("LD_PRELOAD");
        if (preload && preload[0]) {
            std::string cleaned;
            std::string orig(preload);
            size_t start = 0;
            while (start < orig.size()) {
                size_t colon = orig.find(':', start);
                if (colon == std::string::npos) colon = orig.size();
                std::string entry = orig.substr(start, colon - start);
                // Keep entries that are NOT the gameoverlayrenderer
                if (!entry.empty() &&
                    entry.find("gameoverlayrenderer") == std::string::npos) {
                    if (!cleaned.empty()) cleaned += ':';
                    cleaned += entry;
                }
                start = colon + 1;
            }
            if (cleaned != orig) {
                if (cleaned.empty())
                    unsetenv("LD_PRELOAD");
                else
                    setenv("LD_PRELOAD", cleaned.c_str(), 1);
            }
        }
    }

    // Raise the memory-locking limit.  Wine/yabridge need to mlock pages
    // for real-time audio.  The Steam Deck default is only 64 KB which
    // causes "low memory locking limit" warnings and audio silence.
    {
        struct rlimit rl;
        if (getrlimit(RLIMIT_MEMLOCK, &rl) == 0) {
            if (rl.rlim_cur < rl.rlim_max) {
                rl.rlim_cur = rl.rlim_max;
                setrlimit(RLIMIT_MEMLOCK, &rl);
            }
            if (rl.rlim_cur != RLIM_INFINITY && rl.rlim_cur < 256u * 1024 * 1024) {
                struct rlimit unlim;
                unlim.rlim_cur = RLIM_INFINITY;
                unlim.rlim_max = RLIM_INFINITY;
                if (setrlimit(RLIMIT_MEMLOCK, &unlim) != 0) {
                    // Try sudo prlimit (Steam Deck has passwordless sudo)
                    char cmd[256];
                    snprintf(cmd, sizeof(cmd),
                             "sudo prlimit --pid %d "
                             "--memlock=unlimited:unlimited 2>/dev/null",
                             (int)getpid());
                    FILE *pp = popen(cmd, "r");
                    if (pp) {
                        char buf[256];
                        while (fgets(buf, sizeof(buf), pp)) {}
                        int ret = pclose(pp);
                        if (ret == 0) {
                            if (getrlimit(RLIMIT_MEMLOCK, &rl) == 0) {
                                if (rl.rlim_cur < rl.rlim_max ||
                                    rl.rlim_max == RLIM_INFINITY) {
                                    rl.rlim_cur = rl.rlim_max;
                                    setrlimit(RLIMIT_MEMLOCK, &rl);
                                }
                            }
                        }
                    }
                    // Create limits.d file for future boots
                    const char *limitsFile =
                        "/etc/security/limits.d/99-memlock.conf";
                    struct stat limSt;
                    if (stat(limitsFile, &limSt) != 0) {
                        system(
                            "sudo sh -c 'echo \"* - memlock unlimited\" "
                            "> /etc/security/limits.d/99-memlock.conf' "
                            "2>/dev/null");
                    }
                }
            }
        }
    }

    // Create ~/.vst3/win/ directory if it doesn't exist
    std::string vst3WinDir = std::string(home) + "/.vst3/win";
    struct stat st;
    if (stat(vst3WinDir.c_str(), &st) != 0) {
        // Create parent directory first if needed
        std::string vst3Dir = std::string(home) + "/.vst3";
        if (stat(vst3Dir.c_str(), &st) != 0) {
            if (mkdir(vst3Dir.c_str(), 0755) != 0)
                return;
        }
        if (mkdir(vst3WinDir.c_str(), 0755) != 0)
            return;
    }

    // Find Proton wine binary
    std::string winePath = findProtonWine(home);
    if (winePath.empty())
        return;

    // Export WINELOADER so that the yabridge chainloader (triggered by dlopen
    // when the user actually loads a bridged plugin) can find Wine/Proton.
    setenv("WINELOADER", winePath.c_str(), 1);

    // Proton's wine binary links against libs in its own files/lib{,64}.
    // Without these on LD_LIBRARY_PATH the binary (and yabridge-host.exe)
    // will fail to resolve symbols at runtime on a stock Steam Deck.
    // We derive the Proton base from the wine path:
    //   .../Proton X.Y/files/bin/wine  ->  .../Proton X.Y
    std::string protonBase;
    {
        // winePath = .../files/bin/wine  or  .../dist/bin/wine
        std::string tmp = winePath;
        // Strip "/wine"
        size_t sl = tmp.rfind('/');
        if (sl != std::string::npos) tmp = tmp.substr(0, sl);
        // Strip "/bin"
        sl = tmp.rfind('/');
        if (sl != std::string::npos) tmp = tmp.substr(0, sl);
        // Strip "/files" or "/dist"
        sl = tmp.rfind('/');
        if (sl != std::string::npos) tmp = tmp.substr(0, sl);
        protonBase = tmp;
    }

    // Build LD_LIBRARY_PATH additions from Proton's lib directories
    // Also determine the sub-tree root (files/ or dist/) for later use.
    std::string subTree;
    {
        // Determine which sub-tree the wine binary is in (files/ or dist/)
        if (winePath.find("/files/bin/") != std::string::npos)
            subTree = protonBase + "/files";
        else
            subTree = protonBase + "/dist";

        std::string libDirs = subTree + "/lib:" + subTree + "/lib64";

        const char *existing = getenv("LD_LIBRARY_PATH");
        std::string newLdPath = libDirs;
        if (existing && existing[0] != '\0') {
            newLdPath += ":";
            newLdPath += existing;
        }
        setenv("LD_LIBRARY_PATH", newLdPath.c_str(), 1);
    }

    // Set WINEDLLPATH so Proton's Wine can locate its PE builtin DLLs.
    // Without this, Wine cannot find d2d1.dll, dwrite.dll, d3d11.dll etc.
    // The Proton `proton` script normally sets this; since we bypass the
    // script we must do it ourselves.
    {
        // Proton stores PE DLLs in lib64/wine/x86_64-windows (64-bit)
        // and lib/wine/i386-windows (32-bit).  Also add the dxvk and
        // vkd3d-proton directories.
        std::string dllPath64 = subTree + "/lib64/wine/x86_64-windows";
        std::string dllPath32 = subTree + "/lib/wine/i386-windows";
        std::string dxvk64    = subTree + "/lib64/wine/dxvk";
        std::string vkd3d64   = subTree + "/lib64/wine/vkd3d-proton";

        std::string wineDllPath = dllPath64 + ":" + dxvk64 + ":" +
                                  vkd3d64 + ":" + dllPath32;

        const char *existing = getenv("WINEDLLPATH");
        if (existing && existing[0] != '\0') {
            wineDllPath += ":";
            wineDllPath += existing;
        }
        setenv("WINEDLLPATH", wineDllPath.c_str(), 1);
    }

    // Set WINESERVER to match the Proton installation.
    {
        std::string wineserver = subTree + "/bin/wineserver";
        struct stat wsSt;
        if (stat(wineserver.c_str(), &wsSt) == 0)
            setenv("WINESERVER", wineserver.c_str(), 1);
    }

    // Also put the yabridge directory on PATH so the chainloader can
    // find yabridge-host.exe (it's a winelib app that the bridge
    // library spawns via execvp).
    {
        std::string yabDir =
            std::string(home) + "/Documents/SDTracker/yabridge";
        const char *existingPath = getenv("PATH");
        std::string newPath = yabDir;
        if (existingPath && existingPath[0] != '\0') {
            newPath += ":";
            newPath += existingPath;
        }
        setenv("PATH", newPath.c_str(), 1);
    }

    // Set up a dedicated WINEPREFIX for yabridge.  Without this the Wine
    // host process falls back to ~/.wine which usually doesn't exist on a
    // Steam Deck.  We keep the prefix alongside our other app data.
    std::string winePrefix =
        std::string(home) + "/Documents/SDTracker/wineprefix";
    setenv("WINEPREFIX", winePrefix.c_str(), 1);
    setenv("WINEFSYNC", "1", 0); // enable fsync if available (don't override)
    // Suppress Wine debug output.  Without this, Wine logs hundreds of
    // "fixme:unwind:execute_cfa_instructions unknown CFA opcode" messages
    // during Serum 2 preset loading.  Each log call consumes stack space
    // on the unwinder thread, and 468+ of them overflow Wine's 1 MB thread
    // stack, crashing the host process and killing SDTracker (SIGABRT/134).
    setenv("WINEDEBUG", "-all", 0);  // don't override if user set it
    // Tell Wine to prefer native (DXVK) versions of Direct3D DLLs over
    // its own builtins.  This is what Proton normally does via the proton
    // script.  Without this, Wine may load its stub DLLs which don't
    // implement enough of D3D11 for Serum 2 to initialise.
    // Use flag=1 to FORCE override — Steam may have already set
    // WINEDLLOVERRIDES to a partial value like "dxgi=n" which
    // doesn't cover d3d11, d2d1, dwrite, etc.
    setenv("WINEDLLOVERRIDES",
           "dxgi,d3d11,d3d10core,d3d10_1,d3d10,d3d9=n,b;"
           "d2d1,dwrite=b,n", 1);

    // Initialise the prefix if it doesn't exist yet.
    // Prefer using the Proton `proton` script which handles all the
    // internal Wine environment setup (library paths, registry, etc.).
    // Fall back to calling wineboot directly for non-Proton Wine.
    //
    // Also force re-creation if DXVK wasn't properly set up — detected
    // by checking whether dxgi.dll is a real DXVK DLL (>100KB) vs a
    // Wine fake/stub DLL (typically <10KB).
    {
        struct stat pfxSt;
        bool needsBoot = false;
        if (stat(winePrefix.c_str(), &pfxSt) != 0) {
            needsBoot = true;
        } else {
            // Prefix directory exists — check for system.reg as a
            // quick "is it actually initialised?" test.
            std::string sysReg = winePrefix + "/system.reg";
            if (stat(sysReg.c_str(), &pfxSt) != 0)
                needsBoot = true;
        }

        // Even if the prefix exists, check that DXVK is properly
        // installed.  Serum 2 needs d3d11.dll/dxgi.dll which come
        // from DXVK (Proton installs them).  If they're missing or
        // are tiny Wine stubs (<100KB), we need to re-create the prefix.
        if (!needsBoot) {
            // Check the pfx/ subdirectory too (Proton layout)
            std::string checkPrefix = winePrefix;
            std::string pfxSub = winePrefix + "/pfx";
            struct stat subSt;
            if (stat((pfxSub + "/system.reg").c_str(), &subSt) == 0)
                checkPrefix = pfxSub;

            std::string dxgiPath = checkPrefix +
                "/drive_c/windows/system32/dxgi.dll";
            struct stat dxgiSt;
            if (stat(dxgiPath.c_str(), &dxgiSt) != 0) {
                needsBoot = true;
            } else if (dxgiSt.st_size < 100 * 1024) {
                needsBoot = true;
            }

            if (needsBoot) {
                std::string rmCmd = "rm -rf \"" + winePrefix + "\"";
                system(rmCmd.c_str());
            }
        }

        if (needsBoot) {
            std::string bootCmd;
            std::string protonScript = protonBase + "/proton";
            struct stat psSt;

            if (stat(protonScript.c_str(), &psSt) == 0 &&
                S_ISREG(psSt.st_mode)) {
                std::string compatData = winePrefix;
                bootCmd =
                    "STEAM_COMPAT_DATA_PATH=\"" + compatData +
                    "\" STEAM_COMPAT_CLIENT_INSTALL_PATH=\"" +
                    std::string(home) + "/.steam/steam"
                    "\" DISPLAY= WAYLAND_DISPLAY="
                    " python3 \"" + protonScript + "\" run wineboot -u 2>&1";
            } else {
                std::string wineDir = winePath;
                size_t slashPos = wineDir.rfind('/');
                if (slashPos != std::string::npos)
                    wineDir = wineDir.substr(0, slashPos);
                std::string wineboot = wineDir + "/wineboot";

                struct stat wbSt;
                if (stat(wineboot.c_str(), &wbSt) != 0)
                    wineboot = "wineboot";

                bootCmd = "WINELOADER=\"" + winePath +
                          "\" WINEPREFIX=\"" + winePrefix +
                          "\" WINEFSYNC=1"
                          " DISPLAY= WAYLAND_DISPLAY="
                          " \"" + wineboot + "\" -u 2>&1";
            }

            FILE *bootPipe = popen(bootCmd.c_str(), "r");
            if (bootPipe) {
                char line[256];
                while (fgets(line, sizeof(line), bootPipe)) {}
                pclose(bootPipe);
            }
        }
    }

    // Check for Proton's pfx/ sub-directory layout and redirect
    // WINEPREFIX if needed.
    {
        const char *subPaths[] = { "/pfx", "/pfx/pfx", NULL };
        for (int i = 0; subPaths[i]; i++) {
            std::string pfxSub = winePrefix + subPaths[i];
            std::string pfxSysReg = pfxSub + "/system.reg";
            std::string pfxDxgi = pfxSub + "/drive_c/windows/system32/dxgi.dll";
            struct stat pfxRedirSt;
            if (stat(pfxSysReg.c_str(), &pfxRedirSt) == 0 ||
                stat(pfxDxgi.c_str(), &pfxRedirSt) == 0) {
                winePrefix = pfxSub;
                setenv("WINEPREFIX", winePrefix.c_str(), 1);
                break;
            }
        }
    }

    // If the Wine prefix was created by Proton (user "steamuser") but the
    // host system user is different, create a symlink so plugins like u-he
    // Diva can find their data in C:\users\<host-user>\Documents.
    {
        const char *hostUser = getenv("USER");
        if (!hostUser) hostUser = getenv("LOGNAME");
        if (hostUser && hostUser[0] && strcmp(hostUser, "steamuser") != 0) {
            std::string usersDir = winePrefix + "/drive_c/users";
            std::string steamDir = usersDir + "/steamuser";
            std::string hostDir  = usersDir + "/" + hostUser;
            struct stat steamSt, hostSt;
            if (stat(steamDir.c_str(), &steamSt) == 0 &&
                S_ISDIR(steamSt.st_mode)) {
                if (lstat(hostDir.c_str(), &hostSt) != 0)
                    symlink("steamuser", hostDir.c_str());
            }
        }
    }

    // Copy essential DLLs that Proton's default prefix ships but that our
    // wineboot-created prefix may be missing.  Serum 2 (and other GPU-using
    // plugins) link against d3d11.dll → dxgi.dll and d2d1.dll for their
    // GUI rendering.  Even when running headless, the DLLs must be present
    // or Wine will refuse to load the plugin module at all.
    {
        std::string defaultPfx = protonBase + "/files/share/default_pfx";
        const char *dllNames[] = {
            // Direct3D / DXGI (provided by DXVK/vkd3d-proton in Proton)
            "dxgi.dll",
            "d3d11.dll",
            "d3d10core.dll",
            "d3d10_1.dll",
            "d3d10.dll",
            "d3d9.dll",
            // Direct2D / DirectWrite (used by Serum 2 for GUI text)
            "d2d1.dll",
            "dwrite.dll",
            // vkd3d (Vulkan-based D3D12, sometimes a dependency)
            "libvkd3d-1.dll",
            "libvkd3d-shader-1.dll",
        };
        const char *subdirs[] = { "system32", "syswow64" };
        for (size_t s = 0; s < sizeof(subdirs) / sizeof(subdirs[0]); s++) {
            std::string ourDir  = winePrefix + "/drive_c/windows/" + subdirs[s];
            std::string srcDir  = defaultPfx + "/drive_c/windows/" + subdirs[s];
            struct stat dirSt;
            if (stat(ourDir.c_str(), &dirSt) != 0) continue; // subdir doesn't exist

            // Proton stores DXVK/vkd3d DLLs in multiple possible locations
            bool is64 = (strcmp(subdirs[s], "system32") == 0);
            std::string dxvkDir = protonBase + "/files/lib" +
                                  (is64 ? "64" : "") + "/wine/dxvk";
            std::string vkd3dDir = protonBase + "/files/lib" +
                                   (is64 ? "64" : "") + "/wine/vkd3d-proton";

            for (size_t d = 0; d < sizeof(dllNames) / sizeof(dllNames[0]); d++) {
                std::string dst = ourDir  + "/" + dllNames[d];

                // Try source locations — prioritise DXVK/vkd3d-proton dirs
                // over default_pfx, because default_pfx may contain Wine's
                // builtin PE "fakes" rather than real DXVK DLLs.
                std::string sources[] = {
                    dxvkDir  + "/" + dllNames[d],  // DXVK dir (real DXVK)
                    vkd3dDir + "/" + dllNames[d],  // vkd3d-proton dir
                    srcDir   + "/" + dllNames[d],  // default_pfx (fallback)
                };
                std::string src;
                off_t srcSize = 0;
                for (size_t i = 0; i < 3; i++) {
                    struct stat srcSt;
                    if (stat(sources[i].c_str(), &srcSt) == 0) {
                        src = sources[i];
                        srcSize = srcSt.st_size;
                        break;
                    }
                }
                if (src.empty())
                    continue;

                // Always overwrite from DXVK/vkd3d-proton dirs even if the
                // destination already exists.
                struct stat dstSt;
                bool dstExists = (stat(dst.c_str(), &dstSt) == 0);
                if (dstExists && dstSt.st_size == srcSize)
                    continue;

                FILE *sf = fopen(src.c_str(), "rb");
                if (!sf) continue;
                FILE *df = fopen(dst.c_str(), "wb");
                if (!df) { fclose(sf); continue; }
                char cpBuf[8192];
                size_t n;
                while ((n = fread(cpBuf, 1, sizeof(cpBuf), sf)) > 0)
                    fwrite(cpBuf, 1, n, df);
                fclose(sf); fclose(df);
                chmod(dst.c_str(), 0755);
            }
        }
    }

    // Write DLL override entries into the Wine registry.
    // WINEDLLOVERRIDES env var should work, but some Wine/Proton builds
    // ignore it or yabridge may not propagate it to the Wine host process.
    // Writing directly into system.reg ensures Wine always knows to load
    // DXVK DLLs as "native" rather than trying (and failing) to use its
    // own builtins.
    {
        std::string sysReg = winePrefix + "/system.reg";
        struct stat srSt;
        if (stat(sysReg.c_str(), &srSt) == 0) {
            // Read the existing system.reg
            FILE *rf = fopen(sysReg.c_str(), "r");
            if (rf) {
                std::string content;
                char buf[4096];
                size_t n;
                while ((n = fread(buf, 1, sizeof(buf), rf)) > 0)
                    content.append(buf, n);
                fclose(rf);

                // Check if DllOverrides section already has dxgi
                bool hasDxgiOverride =
                    content.find("\"dxgi\"=\"native\"") != std::string::npos ||
                    content.find("\"*dxgi\"=\"native\"") != std::string::npos;

                if (!hasDxgiOverride) {
                    // Find or create the [Software\\Wine\\DllOverrides] section
                    const char *overrideKey =
                        "[Software\\\\Wine\\\\DllOverrides]";
                    size_t pos = content.find(overrideKey);

                    std::string entries =
                        "\"d2d1\"=\"native\"\n"
                        "\"d3d10\"=\"native\"\n"
                        "\"d3d10_1\"=\"native\"\n"
                        "\"d3d10core\"=\"native\"\n"
                        "\"d3d11\"=\"native\"\n"
                        "\"d3d9\"=\"native\"\n"
                        "\"dwrite\"=\"native\"\n"
                        "\"dxgi\"=\"native\"\n";

                    if (pos != std::string::npos) {
                        // Section exists — insert entries after the section
                        // header line (find the next newline)
                        size_t eol = content.find('\n', pos);
                        if (eol != std::string::npos) {
                            content.insert(eol + 1, entries);
                        }
                    } else {
                        // Section doesn't exist — append it
                        content += "\n";
                        content += overrideKey;
                        content += " 0\n";
                        content += entries;
                        content += "\n";
                    }

                    FILE *wf = fopen(sysReg.c_str(), "w");
                    if (wf) {
                        fwrite(content.data(), 1, content.size(), wf);
                        fclose(wf);
                    }
                }
            }
        }

        // Also write to user.reg as some Wine versions check there
        std::string userReg = winePrefix + "/user.reg";
        if (stat(userReg.c_str(), &srSt) == 0) {
            FILE *rf = fopen(userReg.c_str(), "r");
            if (rf) {
                std::string content;
                char buf[4096];
                size_t n;
                while ((n = fread(buf, 1, sizeof(buf), rf)) > 0)
                    content.append(buf, n);
                fclose(rf);

                bool hasDxgiOverride =
                    content.find("\"dxgi\"=\"native\"") != std::string::npos ||
                    content.find("\"*dxgi\"=\"native\"") != std::string::npos;

                if (!hasDxgiOverride) {
                    const char *overrideKey =
                        "[Software\\\\Wine\\\\DllOverrides]";
                    size_t pos = content.find(overrideKey);

                    std::string entries =
                        "\"d2d1\"=\"native\"\n"
                        "\"d3d10\"=\"native\"\n"
                        "\"d3d10_1\"=\"native\"\n"
                        "\"d3d10core\"=\"native\"\n"
                        "\"d3d11\"=\"native\"\n"
                        "\"d3d9\"=\"native\"\n"
                        "\"dwrite\"=\"native\"\n"
                        "\"dxgi\"=\"native\"\n";

                    if (pos != std::string::npos) {
                        size_t eol = content.find('\n', pos);
                        if (eol != std::string::npos) {
                            content.insert(eol + 1, entries);
                        }
                    } else {
                        content += "\n";
                        content += overrideKey;
                        content += " 0\n";
                        content += entries;
                        content += "\n";
                    }

                    FILE *wf = fopen(userReg.c_str(), "w");
                    if (wf) {
                        fwrite(content.data(), 1, content.size(), wf);
                        fclose(wf);
                    }
                }
            }
        }
    }

    // Ensure the standard Windows VST3 install directory exists inside the
    // Wine prefix so that Windows installers (run via Wine) drop .vst3
    // bundles in the expected location and we can discover them.
    {
        std::string cfVst3 = winePrefix + "/drive_c/Program Files/Common Files/VST3";
        struct stat vst3St;
        if (stat(cfVst3.c_str(), &vst3St) != 0) {
            std::string mkCmd = "mkdir -p \"" + cfVst3 + "\"";
            system(mkCmd.c_str());
        }
    }

    // Extract embedded yabridge into ~/Documents/SDTracker/yabridge/ if needed
    extractEmbeddedYabridge(home);

    // Locate yabridge yabridgectl binary
    // Look in root: (~/Documents/SDTracker/) first, then fall back to bin:
    const char *candidates[] = {"root:yabridge/yabridgectl",
                                "bin:yabridge/yabridgectl",
                                "bin:../yabridge/yabridgectl"};

    Path yabridgectlPath;
    bool found = false;
    for (size_t i = 0; i < sizeof(candidates) / sizeof(candidates[0]); i++) {
        Path candidate(candidates[i]);
        if (FileSystem::GetInstance()->GetFileType(
                candidate.GetPath().c_str()) == FT_FILE) {
            yabridgectlPath = candidate;
            found = true;
            break;
        }
    }

    if (!found)
        return;

    std::string yabridgectlBin = yabridgectlPath.GetCanonicalPath();

    // Derive the yabridge lib directory (same dir as yabridgectl)
    std::string yabridgeLibDir = yabridgectlBin;
    size_t lastSlashPos = yabridgeLibDir.rfind('/');
    if (lastSlashPos != std::string::npos) {
        yabridgeLibDir = yabridgeLibDir.substr(0, lastSlashPos);
    }

    // Write yabridgectl config so it knows where our bundled .so files are.
    // The CLI `yabridgectl set --path` crashes in yabridge 5.1.1 so we write
    // the config TOML directly to ~/.config/yabridgectl/config.toml
    std::string configDir = std::string(home) + "/.config/yabridgectl";
    std::string configPath = configDir + "/" + "config.toml";
    struct stat cfgSt;
    if (stat(configDir.c_str(), &cfgSt) != 0) {
        std::string mkdirCmd =
            "mkdir -p \"" + configDir + "\"";
        (void)system(mkdirCmd.c_str());
    }

    // Collect all plugin directories: our manual ~/.vst3/win/ dir plus the
    // standard Windows VST3 install locations inside the Wine prefix so
    // users can run a Windows installer (via Wine) and have the plugin
    // discovered automatically.
    std::vector<std::string> pluginDirs;
    pluginDirs.push_back(vst3WinDir);
    {
        // Standard Windows VST3 paths mapped into the Wine prefix
        const char *winVst3Subdirs[] = {
            "/drive_c/Program Files/Common Files/VST3",
            "/drive_c/Program Files (x86)/Common Files/VST3",
        };
        for (size_t i = 0; i < sizeof(winVst3Subdirs)/sizeof(winVst3Subdirs[0]); i++) {
            std::string d = winePrefix + winVst3Subdirs[i];
            struct stat dst;
            if (stat(d.c_str(), &dst) == 0 && S_ISDIR(dst.st_mode))
                pluginDirs.push_back(d);
        }
    }

    // Read existing config to preserve user settings, but always update path
    // and ensure our plugin_dirs entries are present
    {
        std::string toml;
        toml += "yabridge_home = '" + yabridgeLibDir + "'\n";
        toml += "plugin_dirs = [";
        for (size_t i = 0; i < pluginDirs.size(); i++) {
            if (i > 0) toml += ", ";
            toml += "'" + pluginDirs[i] + "'";
        }
        toml += "]\n";
        toml += "vst2_location = 'centralized'\n";
        toml += "no_verify = false\n";
        toml += "blacklist = []\n";

        FILE *cfgFile = fopen(configPath.c_str(), "w");
        if (cfgFile) {
            fwrite(toml.c_str(), 1, toml.size(), cfgFile);
            fclose(cfgFile);
        }
    }

    // Create ~/.local/share/yabridge symlink pointing to our bundled directory.
    // The yabridge chainloader .so inside bridged plugins searches for
    // libyabridge-vst3.so (and yabridge-host.exe) in $PATH and
    // ~/.local/share/yabridge/. Without this symlink the chainloader can't find
    // the actual bridge library at runtime.
    {
        std::string shareDir = std::string(home) + "/.local/share";
        std::string symlinkPath = shareDir + "/yabridge";

        // Create ~/.local/share if needed
        struct stat shareSt;
        if (stat(shareDir.c_str(), &shareSt) != 0) {
            std::string mkShareCmd = "mkdir -p \"" + shareDir + "\"";
            (void)system(mkShareCmd.c_str());
        }

        // Check if symlink already points to the right place
        char linkTarget[1024];
        ssize_t linkLen =
            readlink(symlinkPath.c_str(), linkTarget, sizeof(linkTarget) - 1);
        bool needSymlink = true;
        if (linkLen > 0) {
            linkTarget[linkLen] = '\0';
            if (std::string(linkTarget) == yabridgeLibDir) {
                needSymlink = false;
            } else {
                // Symlink exists but points elsewhere — remove it
                unlink(symlinkPath.c_str());
            }
        } else {
            struct stat linkSt;
            if (lstat(symlinkPath.c_str(), &linkSt) == 0 &&
                S_ISDIR(linkSt.st_mode))
                needSymlink = false;
        }

        if (needSymlink)
            symlink(yabridgeLibDir.c_str(), symlinkPath.c_str());
    }

    // Run yabridgectl add for each plugin directory
    for (size_t pd = 0; pd < pluginDirs.size(); pd++) {
        std::string addCmd =
            "\"" + yabridgectlBin + "\" add \"" + pluginDirs[pd] + "\" 2>&1";
        FILE *addPipe = popen(addCmd.c_str(), "r");
        if (addPipe) {
            char line[256];
            while (fgets(line, sizeof(line), addPipe)) {}
            pclose(addPipe);
        }
    }

    // Run WINELOADER="..." yabridgectl sync
    std::string syncCmd =
        "WINELOADER=\"" + winePath + "\" \"" + yabridgectlBin + "\" sync 2>&1";
    FILE *syncPipe = popen(syncCmd.c_str(), "r");
    if (syncPipe) {
        char line[256];
        while (fgets(line, sizeof(line), syncPipe)) {}
        int syncResult = pclose(syncPipe);
        if (syncResult == 0) {
            for (size_t pd = 0; pd < pluginDirs.size(); pd++)
                propagateModuleInfo(home, pluginDirs[pd]);
        }
    }
}
