#include "Config.h"
#include <sys/stat.h>
#include <fstream>


Config::Config() 
{
	// Load configuration from the user Documents SDTracker folder via the `root:` alias
	Path path("root:config.xml") ;
	
	TiXmlDocument *document=new TiXmlDocument(path.GetPath());
	bool loadOkay = document->LoadFile();

	// If loading from root alias failed (alias maybe not set yet), fall back to bin:config.xml
	if (!loadOkay) {
		
		delete document;
		Path path2("bin:config.xml");
		
		document = new TiXmlDocument(path2.GetPath());
		loadOkay = document->LoadFile();
	}

	if (loadOkay)
  { 
		// Check first node is CONFIG/ GPCONFIG

		TiXmlNode* rootnode = 0;

		rootnode = document->FirstChild( "CONFIG" );
		if (!rootnode)
    {
		   rootnode = document->FirstChild( "GPCONFIG" );
    }
    
		if (rootnode)
    {
			TiXmlElement *rootelement = rootnode->ToElement();
			TiXmlNode *node = rootelement->FirstChildElement() ;

			// Loop on all children
		
			if (node)
      {
				TiXmlElement *element = node->ToElement();
				while (element) 
        {
					const char *key=element->Value() ;
					const char *value=element->Attribute("value") ;
					if (!value)
          {
						value=element->Attribute("VALUE") ;
					}
					if (key&&value)
          {
						Variable *v=new Variable(key,0,value) ;
						Insert(v) ;
					}
					element = element->NextSiblingElement(); 
				}
			}

    }
	} else {
		

		// Attempt to write a sensible default config into root:config.xml
		Path p("root:config.xml");
		std::string configPath = p.GetPath();

		// Ensure parent directory exists (best-effort)
		size_t pos = configPath.find_last_of('/');
		if (pos!=std::string::npos) {
			std::string dir = configPath.substr(0,pos);
			struct stat st ;
			if (stat(dir.c_str(),&st)!=0) {
				mkdir(dir.c_str(),0755);
			}
		}

		const char *defaultConfig = R"(<!-- Default config generated by application -->
<CONFIG>
	<DUMPEVENT value="YES"/>
	<SCREENMULT value="1"/>
	<BACKGROUND   value = "000000" />
	<FOREGROUND   value = "F5EBFF" />
	<BORDER       value = "FF00DD" />
	<HICOLOR1     value = "B750D1" />
	<HICOLOR2     value = "DB33DB" />
	<SONGVIEW_FE  value = "A55B8F" />
	<SONGVIEW_00  value = "853B6F" />
	<CURSORCOLOR  value = "FF00DD" />
	<PLAYCOLOR    value = "FF00DD" />
	<MUTECOLOR    value = "F5EBFF" />
	<ROWCOLOR1    value = "BA28F9" />
	<ROWCOLOR2    value = "FF00FF" />
	<ALTROWNUMBER value = "4"/>
	<FONTTYPE     value = '0' />
</CONFIG>
)";

		std::ofstream out(configPath.c_str());
		if (out) {
			out << defaultConfig;
			out.close();
			

			// Try loading it now
			delete document;
			document = new TiXmlDocument(configPath);
			loadOkay = document->LoadFile();
		} else {
			
		}
	}
 	delete(document) ;
}


//------------------------------------------------------------------------------

Config::~Config()
{
}


//------------------------------------------------------------------------------

const char *Config::GetValue(const char *key) 
{
	Variable *v=FindVariable(key) ;
	if (v) {
		
	}
	return v?v->GetString():0 ;
} ;


//------------------------------------------------------------------------------

void Config::ProcessArguments(int argc,char **argv) 
{
	for (int i=1;i<argc;i++) {
		char *pos ;
		char *arg=argv[i] ;
		while (*arg=='-') arg++ ;
		if ((pos=strchr(arg,'='))!=0) {
			*pos=0 ;
			Variable *v=FindVariable(arg) ;
			if (v) {
				v->SetString(pos+1) ;
			} else {
				Variable *v=new Variable(arg,0,pos+1) ;
				Insert(v) ;
			}
		}
	}
} ;


//------------------------------------------------------------------------------
